language: node_js

os:
  - osx

node_js:
  - "6"
  - "8"
  - "10"
  - "11"

install:
  - npm install -g -q gulp istanbul &> /dev/null
  - npm install -q --unsafe-perm=true

script: "gulp coverage-export"

notifications:
  email: false