language: node_js
node_js:
  - "5"
  - "6"
  - "7"
cache:
  directories:
    - node_modules
before_script:
  - npm install -g gulp istanbul --silent
script: "gulp coverage-export"
notifications:
  email: false