environment:
  matrix:
    # node.js
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g gulp --silent
  - npm install --silent

#build_script:
#  - gulp build

test_script:
  - node --version
  - npm --version
  - gulp appveyor

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = '.\coverage\JUnit.xml'
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $file))

build: off