image:
  - Visual Studio 2015
  - Ubuntu

environment:
  matrix:
    # node.js
    - nodejs: "6"
    - nodejs: "8"
    - nodejs: "10"
    - nodejs: "11"

install:
  - cmd: powershell Install-Product node $env:nodejs x64
  - sh: nvm install $nodejs
  - node -p "[process.version,process.arch].join(' ')"
  - cmd: npm install -g -q gulp >nul
  - sh: npm install -g -q gulp &> /dev/null
  - npm install -q --unsafe-perm=true

test_script:
  - gulp appveyor

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = '.\coverage\JUnit.xml'
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $file))

skip_commits:
  files:
    - .idea/*
    - '**/*.md'
    - '**/*.d.ts'
    - '**/*.gif'
    - '**/*.png'
    - '.travis.yml'

build: off