image:
  - Visual Studio 2022
  - Ubuntu2204
  - macos-monterey

environment:
  matrix:
    - nodejs: "20"

install:
  - cmd: powershell Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs) x64
  - sh: nvm ls
  - sh: nvm use $nodejs || nvm install $nodejs
  - cmd: npm install -g -q gulp >nul
  - sh: npm install -g -q gulp &> /dev/null
  - npm install -q --unsafe-perm=true

test_script:
  - gulp appveyor

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = '.\coverage\JUnit.xml'
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $file))

skip_commits:
  files:
    - .idea
    - '**/*.md'
    - '**/*.d.ts'
    - '**/*.gif'
    - '**/*.png'
    - LICENSE
    - .gitignore

build: off

cache:
  - node_modules -> package.json