name: Test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/FUNDING.YML'
      - '.github/dependabot.yml'
      - '**/*.md'
      - '.gitconfig'
      - '.gitignore'
      - '.npmignore'
      - 'LICENSE*'
      - '.idea/**'
      - '.vscode/**'
      - 'README.md'
      - 'gulpfile.js'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: test-${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2022]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ matrix.os }}-${{ hashFiles('package-lock.json') }}

      - name: npm install
        run: npm i

      - name: "Run tests"
        run: npm test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-summary (ts-progress ${{ matrix.os }})
          path: coverage/junit.xml

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info

  publish-test-summary:
    name: "publish test-summary"
    needs: test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: publish test-summary
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_run_annotations: 'none'
          check_name: 'test-results'
          files: "artifacts/**/*.xml"